language: erlang
script: rebar --config=rebar.dev.config get-deps && rebar --config=rebar.dev.config compile && rebar --config=rebar.dev.config skip_deps=true eunit
otp_release:
  - R16B
  - R15B02
  - R15B01
  - R15B
